name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numba=0.51.2
  - numexpr=2.7.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - hyperspy=1.6.0
  - nodejs=10.13.0
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_nbextensions_configurator=0.4.1
prefix: /Users/johnmaclennan/opt/anaconda3
